[package]
name = "wdl-grammar"
version = "0.1.0"
authors = ["Clay McLeod <clay.l.mcleod@gmail.com>"]
edition.workspace = true
license.workspace = true
description = "Grammar lexing and parsing for Workflow Description Language (WDL) documents"
homepage = "https://github.com/stjude-rust-labs/wdl"
repository = "https://github.com/stjude-rust-labs/wdl"
documentation = "https://docs.rs/wdl-grammar"

[dependencies]
async-recursion = { version = "1.0.5", optional = true }
chrono = { version = "0.4.31", optional = true }
clap = { workspace = true, optional = true }
colored = { version = "2.0.4", optional = true }
dirs = { version = "5.0.1", optional = true }
env_logger = { workspace = true, optional = true }
indexmap = { workspace = true, optional = true }
log = { workspace = true, optional = true }
octocrab = { version = "0.32.0", optional = true }
pest = { workspace = true }
pest_derive = { workspace = true }
reqwest = { version = "0.11.22", optional = true }
serde = { workspace = true }
serde_with = { workspace = true, optional = true }
to_snake_case = "0.1.1"
tokio = { version = "1.33.0", features = ["full"], optional = true }
toml = { workspace = true, optional = true }

[features]
binaries = [
    "dep:async-recursion",
    "dep:chrono",
    "dep:clap",
    "dep:colored",
    "dep:dirs",
    "dep:env_logger",
    "dep:indexmap",
    "dep:log",
    "dep:octocrab",
    "dep:reqwest",
    "dep:serde_with",
    "dep:tokio",
    "dep:toml",
]

[[bin]]
name = "wdl-grammar"
path = "src/main.rs"
required-features = ["binaries"]
