#[patch.'https://github.com/stjude-rust-labs/wdl']
# [patch.crates-io]
# wdl = { path = "../wdl/wdl" }
# wdl-analysis = { path = "../wdl/wdl-analysis" }
# wdl-ast = { path = "../wdl/wdl-ast" }
# wdl-cli = { path = "../wdl/wdl-cli" }
# wdl-doc = { path = "../wdl/wdl-doc" }
# wdl-engine = { path = "../wdl/wdl-engine" }
# wdl-format = { path = "../wdl/wdl-format" }
# wdl-grammar = { path = "../wdl/wdl-grammar" }
# wdl-lint = { path = "../wdl/wdl-lint" }
# wdl-lsp = { path = "../wdl/wdl-lsp" }

