version = "v1"

[[repositories]]
organization = "PacificBiosciences"
name = "HiFi-human-WGS-WDL"

[[repositories]]
organization = "biowdl"
name = "tasks"

[[repositories]]
organization = "broadinstitute"
name = "warp"

[[repositories]]
organization = "chanzuckerberg"
name = "czid-workflows"

[[repositories]]
organization = "stjudecloud"
name = "workflows"
